### ISSUE TITLE
在使用autolayout的时候，如何保证动画效果合适

### ISSUE THREAD

**Issue by a5511258** [coderliu/iOSAnimationSample#1]
我很喜欢您做的视频教程，动画效果也特别的酷炫，我现在有个问题，在不同屏幕上，如何使用相同的动画，且效果合适？

**Comment by coderliu** [comment]
我只是一个初学者，现在也很长时间没有接触 iOS 开发了，这些例子来自于 [imooc JakeLin 老师的视频](http://www.imooc.com/space/teacher/id/225594) ，这个视频里没有讲到 autolayout 的使用，都是基于iPhone5 的屏幕尺寸讲的例子。用 Storyboard的话，加一些约束就可以了吧。

**Comment by a5511258** [comment]
我尝试了加autolayout，发现并不能实现动画，
我将一个 文字logo（用sketch做的），设置居中（storyboard中），然后在viewDidLoad中设置它的center.x为屏幕外 -88，但是在运行的时候，默认就显示为中间，动画开始也是由中间移除屏幕，我期望是由屏幕外移到中间。
我一直没搞明白 autolayout是在viewController的哪个时间段执行的，感觉像是设置值后又被autolayout覆盖回去了。
